# Generated by Django 5.1.2 on 2024-12-30 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about_me_content",
            name="github_url",
            field=models.URLField(default="https://github.com/klokanpes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about_me_content",
            name="last_edited",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now()
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about_me_content",
            name="linked_in_url",
            field=models.URLField(
                default="https://www.linkedin.com/in/vojt%C4%9Bch-%C4%8Dern%C3%BD-12ab73286/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact_content",
            name="github_url",
            field=models.URLField(default="https://github.com/klokanpes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact_content",
            name="last_edited",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now()
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact_content",
            name="linked_in_url",
            field=models.URLField(
                default="https://www.linkedin.com/in/vojt%C4%9Bch-%C4%8Dern%C3%BD-12ab73286/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage_content",
            name="last_edited",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now()
            ),
            preserve_default=False,
        ),
    ]
