# Generated by Django 5.1.2 on 2024-12-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_website",
            "0003_emailcounter_remove_contact_content_content_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailCounter",
            new_name="Email_counter",
        ),
    ]
