# Generated by Django 5.1.2 on 2025-01-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0004_rename_emailcounter_email_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology_experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
