# Generated by Django 5.1.2 on 2025-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0005_technology_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology_experience",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
