# Generated by Django 5.1.2 on 2025-01-01 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0006_alter_technology_experience_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="email_counter",
            name="current_year",
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projects_content",
            name="created",
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
