# Generated by Django 5.1.2 on 2025-01-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0009_projects_content_youtube_backup_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Terms_and_conditions_agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_cookie", models.TextField()),
                ("ga4_agreement", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Terms_and_conditions_content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
