# Generated by Django 5.1.2 on 2025-01-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_website", "0010_terms_and_conditions_agreement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terms_and_conditions_agreement",
            name="session_cookie",
            field=models.TextField(unique=True),
        ),
    ]
