# Generated by Django 5.1.2 on 2025-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personal_website",
            "0011_alter_terms_and_conditions_agreement_session_cookie",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Darkmode_preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_cookie", models.TextField(unique=True)),
                ("darkmode", models.BooleanField()),
            ],
        ),
    ]
